#ifndef CWHITEBOARD_GLOBAL_H
#define CWHITEBOARD_GLOBAL_H

#if defined(CWHITEBOARD_LIBRARY)
#  define CWHITEBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CWHITEBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // CWHITEBOARD_GLOBAL_H
